apiVersion: database.oracle.com/v1alpha1
kind: PDB
metadata:
  name: txqpdb
  namespace: txq-oradb
  labels:
    cdb: ai23-remote-cdb
    pdb: txqpdb
spec:
  cdbResName: "ai23-cloud-cdb"
  cdbNamespace: "23aidemo"
  cdbName: "DB23ai"
  pdbName: "txqpdb"
  adminName:
    secret:
      secretName: "txqpdb-secret"
      key: "sysadmin_user"
  adminPwd:
    secret:
      secretName: "txqdb-secret"
      key: "sysadmin_pwd"
  webServerPwd:
    secret:
      key: webserver_pwd
      secretName: aicdb-secret
  webServerUser:
    secret:
      key: webserver_user
      secretName: aicdb-secret
  fileNameConversions: NONE
  totalSize: "1G"
  tempSize: "100M"
  action: "Create"
  #action: "Delete"
  #dropAction: "INCLUDING"
  #pdbState: "OPEN"
  #modifyOption: "READ WRITE"
  #pdbState: "CLOSE"
  #modifyOption: "IMMEDIATE"
  #action: "Modify"
  pdbTlsCat:
    secret:
      secretName: "db-ca"
      key: "ca.crt"
  pdbTlsCrt:
    secret:
      secretName: "db-tls"
      key: "tls.crt"
  pdbTlsKey:
    secret:
      secretName: "db-tls"
      key: "tls.key"
