apiVersion: observability.oracle.com/v1alpha1
kind: DatabaseObserver
metadata:
  name: txqpdb-observer
  namespace: txq-oradb
spec:
  database:
    dbUser:
      key: "oracle_user"
      secret: txqpdb-secret

    dbPassword:
      key: "oracle_pwd"
      secret: txqpdb-secret

    dbConnectionString:
      key: "connection1"
      secret: txqpdb-secret


  exporter:
    image: "container-registry.oracle.com/database/observability-exporter:1.3.0"
    service:
      port: 9161
    configuration:
      configmap:
        key: "teq.toml"
        configmapName: "toml-config"
       
  prometheus:
    port: metrics
    labels:
      cdb: ai23-remote-cdb
      pdb: txqpdb

  replicas: 1
