apiVersion: v1
kind: ConfigMap
metadata:
  name: txqpdb-prepare-config
  namespace: txq-oradb
data:
  prepare.sh: |-
    #!/bin/bash 
    sqlplus sys/$DB_PASSWORD@$DB_HOST:1521/$DB_SERVICE as sysdba << EOF 
    alter user pdbadmin quota unlimited on system;
    GRANT EXECUTE on DBMS_AQ to pdbadmin;
    GRANT EXECUTE on DBMS_AQADM to pdbadmin;
    GRANT SELECT on GV_\$SESSION to pdbadmin;
    GRANT SELECT on V_\$SESSION to pdbadmin;
    GRANT SELECT on GV_\$INSTANCE to pdbadmin;
    GRANT SELECT on GV_\$LISTENER_NETWORK to pdbadmin;
    GRANT SELECT on GV_\$PDBS to pdbadmin;
    GRANT SELECT on USER_QUEUE_PARTITION_ASSIGNMENT_TABLE to pdbadmin;    
    exec DBMS_AQADM.GRANT_PRIV_FOR_RM_PLAN('PDBADMIN');
    exit; 
    EOF
  testconn.sh: |-
    #!/bin/bash 
     sqlplus sys/$DB_PASSWORD@$DB_HOST:1521/$DB_SERVICE as sysdba << EOF 
     whenever sqlerror exit failure; 
     select * from dual; 
     exit; 
     EOF
     if [ $? -eq 0 ] ; then echo "connect successful" ; else echo "DB connect failed, waiting 3 min and exiting..." ; sleep 180 ; exit 5 ; fi 
